CREATE TABLE IDSEQUENCE(
	VAL BIGINT
);

CREATE TABLE KOLCSONZES(
	ID BIGINT PRIMARY KEY,
	FILMID BIGINT,
	NAME VARCHAR(100) NOT NULL,
	EXPIRE DATE,
	DATE2 DATE
);

CREATE TABLE FILM(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DIRECTOR VARCHAR(200),
	MAINCAST VARCHAR(200),
	YEAR_OF_RELEASE INTEGER,
	KOLCSON BOOLEAN,
	ORIGINAL BOOLEAN,
	KOLCSONDB BIGINT
);


INSERT INTO IDSEQUENCE (VAL) VALUES (1000);

INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (10,10, 'Nagy Géza','2016-09-12','2016-03-12'); 
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (11,12, 'Gabi','2017-06-12','2017-03-12');
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (12,14, 'David','2017-02-06','2017-01-10');
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (13,16, 'Kis Miklós','2016-03-04','2015-09-12');
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (14,18, 'John Cena','2017-01-12','2017-01-02');
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (15,20, 'Tony Stark','2016-03-12','2016-01-10');
INSERT INTO KOLCSONZES (ID,FILMID, NAME, EXPIRE,DATE2) VALUES (16,22, 'Popey','2015-03-12','2014-02-12');

INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (10, 'Iron Man','','',2008,TRUE,FALSE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (11, 'Thor','','', 2011,FALSE,TRUE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (12, 'Kill Bil','','', 2001,TRUE,FALSE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (13, 'Iron Man 2','','', 2013,FALSE,TRUE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (14, 'Hulk','','', 2005,TRUE,TRUE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (15, 'Wonder Woman','','', 2015,FALSE,TRUE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (16, 'Hulk 2','','', 2006,TRUE,TRUE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (17, 'Captain America','','', 2012,FALSE,FALSE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (18, 'Thor 2','','', 2013,TRUE,TRUE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (19, 'Thor 3','','', 2015,FALSE,TRUE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (20, 'Iron man 3','','', 2016,TRUE,TRUE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (21, 'Daredevil','','', 2009,FALSE,FALSE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (22, 'Justice League','','', 2016,TRUE,TRUE,1);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (23, 'Avengers','','', 2015,FALSE,TRUE,0);
INSERT INTO FILM (ID, NAME, DIRECTOR, MAINCAST, YEAR_OF_RELEASE,KOLCSON,ORIGINAL,KOLCSONDB ) VALUES (24, 'Avengers 2','','', 2016,FALSE,FALSE,0);




